### ISSUE TITLE
Transaction input account annotations not always set properly

### ISSUE THREAD

**Issue by jeffomatic** [chain/chain#668] opened 2017-03-02 19:10 UTC
UPDATE: This affects the following input annotations:

- account_id
- account_alias
- account_tags
- is_local

~@chrisgarvin originally reported an issue where the API was erroneously returning `"is_local": "no"` for transaction inputs that are local to the core. #612 was an attempt to address this issue, but it appears to be ongoing. We're now trying to create a reliable repro case.~

**Comment by jbowens** [comment] 2017-03-02 23:18
The problem is that the tx annotating process uses the `account_control_programs` table for indexing spends. If the ACP expired, it's not guaranteed to still exist despite the account UTXO still being unspent. We can update the tx annotating to use the `account_utxos` table, but we'll need to ferry along the `change` flag.

**Comment by jbowens** [comment] 2017-03-02 23:19
Actually, maybe we don't even need the change flag.

**Comment by jeffomatic** [comment] 2017-03-02 23:20
Ah okay. I'm guessing this actually does more than just cause an incorrect `is_local` flag...it probably omits the entire account annotation on the input, right? If so I can update the original comment in this issue.

**Comment by jbowens** [comment] 2017-03-02 23:27
yeah, the entire account annotation is omitted

**Comment by jbowens** [comment] 2017-03-02 23:35
We are targeting a fix for 1.1.x, right? But not super high priority?

**Comment by jeffomatic** [comment] 2017-03-03 00:02
@jbowens I think we can deprioritize relative to our immediate bugfix push, but since this is an API bug it would be good to retire it as soon as we get the headroom.

**Comment by jbowens** [comment] 2017-03-03 02:11
Fixed on `1.1-stable` but will need a more invasive fix for `main`

**Closed** 2017-03-06 20:08 UTC
Labels: 1.2, bug
